-libraryjars /home/javavirys/WTK2.5.2/lib/mmapi.jar:/home/javavirys/WTK2.5.2/lib/jsr75.jar:/home/javavirys/WTK2.5.2/lib/midpapi20.jar:/home/javavirys/WTK2.5.2/lib/cldcapi11.jar
-injars /home/javavirys/j2mewtk/2.5.2/apps/ReadBigFile/bin/ReadBigFile.jar
-outjar /tmp/ReadBigFile.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
